version: '3.8'

services:
  db:
    image: postgres:15
    container_name: posturepal_db
    restart: always
    environment:
      POSTGRES_USER: posturepal_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posturepal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: