services:
  db:
    image: postgres:15
    restart: always
    container_name: posturepal_db
    environment:
      POSTGRES_USER: posturepal_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posturepal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: