"""Added ExerciseLog table

Revision ID: 13dcccf8d698
Revises: a403c3a9fe92
Create Date: 2025-03-19 03:05:30.447376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13dcccf8d698'
down_revision: Union[str, None] = 'a403c3a9fe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exerciselog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('exercise_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exerciselog')
    # ### end Alembic commands ###
