"""Added More Fields to User model

Revision ID: a403c3a9fe92
Revises: 869412d92c38
Create Date: 2025-03-19 02:08:26.161067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a403c3a9fe92'
down_revision: Union[str, None] = '869412d92c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('height_cm', sa.Float(), nullable=False))
    op.add_column('user', sa.Column('weight_kg', sa.Float(), nullable=False))
    op.add_column('user', sa.Column('daily_calories_burned', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_calories_burned')
    op.drop_column('user', 'weight_kg')
    op.drop_column('user', 'height_cm')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
