"""Added a new field to exercise log model

Revision ID: b5896f210dcc
Revises: 13dcccf8d698
Create Date: 2025-03-21 01:48:36.033817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5896f210dcc'
down_revision: Union[str, None] = '13dcccf8d698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exerciselog', sa.Column('total_reps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciselog', 'total_reps')
    # ### end Alembic commands ###
